---
version: '3.7'

services:

  prepare:
    build:
      context: .
    image: python:3.7
    working_dir: /app
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/app"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-2}
      - AWS_PROFILE
#    entrypoint: bash
#    command:
#    pip3 install -r Martech_API_Automation/requirements.txt

